import React from "react";

export function Jumbotron() {
  return (
    <div className="h-[400px] flex flex-col justify-center items-start pl-4 bg-gray-300 mt-48 mb-10 mx-10">
      <div className="text-center">
        <h1 className="text-8xl">A Warm Welcome!</h1>
      </div>
      <div className="text-2xl text-left mt-4">
        <p>
          Here is a short story generated by AI: Once upon a time, a purple
          giraffe named Geraldine rode a unicycle through a field of cotton
          candy while juggling pineapples. Suddenly, a giant squid wearing a top
          hat appeared and challenged her to a dance-off. Geraldine accepted and
          they battled it out to a disco beat until a flock of flying spaghetti
          monsters swooped in and declared them both winners. The end.
        </p>
      </div>
      <div className="text-center mt-4">
        <button
          className="bg-blue-700 text-white font-bold py-2 px-4 rounded"
          type="button"
        >
          Call to action!
        </button>
      </div>
    </div>
  );
}
