import React from "react";

export function Jumbotron() {
  return (
    <div className="w-fit py-10  flex flex-col justify-center items-start bg-gray-200 mt-48 mb-10 mx-10">
      <div className="text-center px-4">
        <h1 className="lg:text-8xl text-6xl">A Warm Welcome!</h1>
      </div>
      <div className="lg:text-2xl text-xl px-4 text-left mt-4">
        <p>
          Here is a story generated by AI: Binky, Chuckles, Flapjack, and Noodles were all competing to see who
          could sell the most ridiculous item at the fair. Binky sold unicorn
          cheese, Chuckles sold pogo stick cheese, Flapjack sold pirate
          pancakes, and Noodles sold mermaid ice cream. However, they soon
          realized they could combine their products to make even more
          ridiculous concoctions. Together, they created cheesy pirate pancakes,
          unicorn ice cream, mermaid cheese, and pogo stick waffles. The
          fairgoers loved it, and the four became a legendary foodie team. They
          started their own food truck, with a giant pineapple on top, and
          traveled the world, spreading cheesy joy wherever they went.
        </p>
      </div>
      <div className="text-center mt-4 mx-4">
        <button
          className="bg-blue-700 text-white font-bold py-2 px-4 rounded"
          type="button"
        >
          Call to action!
        </button>
      </div>
    </div>
  );
}
